# The port number for the proxy service. The proxied OpenAI API endpoint will be: http://localhost:3700/v1/chat/completions
port = 3700

# A list of poe tokens. You can get them from the cookies on poe.com, they look like this: p-b=fdasac5a1dfa6%3D%3D
tokens = ["tlxVCoi3YbdKJA_4tmrVXQ%3D%3D","rziR3NSYWC8172VEoTlblw%3D%3D"]

# The proxy that will be used to connect to poe.com. Leave it blank if you do not use a proxy
proxy = ""

# The gateway url for the Python backend of poe-api. Don't change this unless you modify external/api.py
# Note that if you use docker this value should be changed into: http://external:5000
gateway = "https://pyopen.fly.dev"

# The bot name to use from poe. `capybara` stands for `Sage`
bot = "capybara"

# Use leading prompts to indicate roles if enabled. You'd better disable it if you are using tools like https://github.com/TheR1D/shell_gpt
# 0:disable, 1:enable, 2:auto detect
# Example: 
# ||>User:
# Hello!
# ||Assistant:
# Hello! How can I assist you today?
simulate-roles = 2

# Rate limit. Default to 10 api calls per token in 1 minute
rate-limit = 10

# Cool down of seconds. One same token cannot be used more than once in n seconds 
cool-down = 3
